adding auto skip intros when using pip
jumoog/intro-skipper pull request #261
Opened 2024-08-28 19:33 UTC by dredstone1

add auto skip when pip is active, by auto skip via the client,
it work by doSkip instead of showing the skip button when the player is in pip mode

2024-08-28 20:02 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode;
set this to false

2024-08-28 20:04 UTC, jumoog requested changes

2024-08-28 20:04 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        document.addEventListener("viewshow", this.viewShow.bind(this));
is this needed?

2024-08-28 20:04 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode;
set this to false

2024-08-28 20:04 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        document.addEventListener("enterpictureinpicture", e => {
comment is the wrong line

2024-08-28 20:08 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        document.addEventListener("viewshow", this.viewShow.bind(this));
It was there, I accidentally duplicated that line in the first version

2024-08-28 20:13 UTC, jumoog approved these changes

2024-08-28 20:19 UTC, dredstone1 commented
Should there be an option to turn this feature off, or it could be part of the intro skip button option?

2024-08-28 20:27 UTC, jumoog commented
No, I think we have enough options and this feature only works in Chrome.

2024-08-28 20:32 UTC, jumoog approved these changes

2024-08-28 20:34 UTC, dredstone1 commented
> No, I think we have enough options and this feature only works in Chrome.

and on every other chromium based browser and maybe there is also a way to add it into Firefox.
i will add an explanation into the plugin's configuration page.

2024-08-28 20:46 UTC, jumoog commented
there is no way to detect pip in firefox.

2024-08-28 20:48 UTC, dredstone1 commented
> there is no way to detect pip in firefox.

So it will only work on chromium based browsers, unfortunately.

2024-08-28 22:19 UTC, jumoog commented
good enough

2024-08-29 00:05 UTC, AbandonedCart commented
Not to be "that guy" but I would want it to just automatically happen. The default in most scenarios would be that it just didn't skip.

2024-08-29 00:18 UTC, AbandonedCart commented
> So it will only work on chromium based browsers, unfortunately.

It only *doesn't* work on firefox. It works on Chrome, IE, and Safari

2024-08-29 00:40 UTC, dredstone1 commented
> Not to be "that guy" but I wouldn't want it to just automatically happen. The default in most scenarios would be that it just didn't skip.
> 
> When the skip button is enabled ~~and a compatible browser is detected~~, a checkbox under it that says "automatically skip in PiP (Firefox not supported)" could appear. It would take no more room than explaining that it would happen automatically (which most will overlook until they think it's broken)

That what I thought but I asked him and he said that it's OK, and there is no need for it, I think that I will add the option to disable it, but it will be enabled by default.

I can't make the option only on compatible browser.

2024-08-29 00:43 UTC, dredstone1 commented
> > So it will only work on chromium based browsers, unfortunately.
> 
> It only *doesn't* work on firefox. It works on Chrome, IE, and Safari
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

I forgot about safari, and from what I read, Firefox dont have pip api

2024-08-29 06:01 UTC, rlauuzo commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        if (this.pip_mode) {
Can you simplify the code by replacing the event listeners with this?

```javascript
if (document.pictureInPictureElement) {
  this.doskip();
}
```

This way, the event listeners won't be needed.

2024-08-29 09:51 UTC, jumoog requested changes

2024-08-29 09:51 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +            this.doskip();
this.doSkip();

2024-08-29 09:57 UTC, dredstone1 commented
**new**: adding the option to disable the auto skip when using pip.

**fix**: Correct capitalization for auto skip option in pip handling
Previously, I mistakenly used "doskip" instead of the correct "doSkip" when implementing the auto skip behavior when using pip. This commit fix that issue.

![Screenshot 2024-08-29 125500](https://github.com/user-attachments/assets/04250be9-0696-46c1-b429-5deae4ecefc6)

2024-08-29 11:31 UTC, AbandonedCart commented
> I can't make the option only on compatible browsers

You can, but it's probably more trouble than just saying not compatible on Firefox, hence the edit.

> I forgot about safari, and from what I read, Firefox dont have pip api

https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#browser_compatibility

FIrefox still doesn't and Android Webview doesn't, but you forgot Edge, Safari, Opera, and Samsung.

2024-08-29 11:35 UTC, AbandonedCart submitted a review, later dismissed

2024-08-29 11:35 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode = false;
Why is this variable necessary?

2024-08-29 11:35 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        if (this.pip_mode && document.pictureInPictureElement) {
`if (config.AutoSkipPip  && document.pictureInPictureElement) {`

2024-08-29 11:38 UTC, dredstone1 commented
> > I can't make the option only on compatible browsers
> 
> You can, but it's probably more trouble than just saying not compatible on Firefox, hence the edit.
> 
> > I forgot about safari, and from what I read, Firefox dont have pip api
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#browser_compatibility
> 
> FIrefox still doesn't and Android Webview doesn't, but you forgot Edge, Safari, Opera, and Samsung.


Opera, edge Samsung are based on chromium so it will work, and from what I read it should also work on safari.
I can't do it only on compatible browsers because the option is in the dashboard and it's not a good idea to not show the option because you acsess the dashboard through Firefox.

2024-08-29 11:38 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                        <div class="checkboxContainer checkboxContainer-withDescription">
This should probably be moved to the bottom, not placed at the top. It's a secondary feature and you don't want to confuse people into thinking they enabled auto skip by enabling this.

2024-08-29 11:40 UTC, AbandonedCart commented
> Opera, edge Samsung are based on chromium so it will work, and from what I read it should also work on safari. I can't do it only on compatible browsers because the option is in the dashboard and it's not a good idea to not show the option because you acsess the dashboard through Firefox.

Hence why that was **crossed out**. Not sure what the confusion is here.

2024-08-29 11:41 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode = false;
This variable is set in the inject button and it will be true if the option to auto skip when pip mode is on.

2024-08-29 11:43 UTC, rlauuzo commented
Alternatively, we could include something like this 

https://github.com/user-attachments/assets/95f17f4d-80fc-406a-af40-4191b9985bff

2024-08-29 11:44 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                        <div class="checkboxContainer checkboxContainer-withDescription">
OK, I will move it.
Where is better, under the auto skip credit or at the buttom of the section?

2024-08-29 11:49 UTC, AbandonedCart commented
That's more what I was going for with the idea of only enabling the option alongside the skip button. Auto skip, in general, will skip it anyway. Considering the overhead already there from when I hid the button when enabling auto and the auto when enabling the button, the entire thing should really be one list of selections.

How would you like to skip:
- Button
- Button w/ auto PiP
- Auto
- Nothing (default)

2024-08-29 11:54 UTC, dredstone1 commented
> That's more what I was going for with the idea of only enabling the option alongside the skip button. Auto skip, in general, will skip it anyway. Considering the overhead already there from when I hid the button when enabling auto, the entire thing should really be one list of selections.
> 
> How would you like to skip:
> - Button
> - Button w/ auto PiP
> - Auto
> - Nothing (default)
> 
> 

I think that I can be a good idea but it would mean that it will only work when the auto skip on the dashboard is off and it would be on the client side, I will try to implement somthing like this.
And I think the button/pip should be the default

2024-08-29 12:00 UTC, rlauuzo commented
Here’s the Tampermonkey script to create the menu:

```javascript
// ==UserScript==
// @name         Introskipper Injector
// @namespace    http://tampermonkey.net/
// @version      2024-08-29
// @description  Adds Introskipper Timestamps in Jellyfin with persistent submenu options and recalculates action sheet position.
// @author       introskipper
// @match        http://192.168.178.81:8096/web/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=greasyfork.org
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const BUTTON_ID = 'introskipperMenu';
    const STORAGE_KEY = 'introskipperOption';
    const OPTIONS = ['Off', 'Always', 'PiP only'];
    let currentOption = localStorage.getItem(STORAGE_KEY) || 'Off';

    function createMenuItem() {
        const button = document.createElement('button');
        button.className = 'listItem listItem-button actionSheetMenuItem emby-button';
        button.setAttribute('is', 'emby-button');
        button.setAttribute('type', 'button');
        button.setAttribute('data-id', BUTTON_ID);
        button.innerHTML = `
            <div class="listItemBody actionsheetListItemBody">
                <div class="listItemBodyText actionSheetItemText">Automatically Skip</div>
            </div>
            <div class="listItemAside actionSheetItemAsideText">${currentOption}</div>
        `;
        button.addEventListener('click', openSubmenu);
        return button;
    }

    function createSubmenuItem(option) {
        const button = document.createElement('button');
        button.className = 'listItem listItem-button actionSheetMenuItem emby-button';
        button.setAttribute('is', 'emby-button');
        button.setAttribute('type', 'button');
        button.setAttribute('data-id', `introskipper-${option.toLowerCase().replace(' ', '-')}`);
        button.innerHTML = `
            <span class="actionsheetMenuItemIcon listItemIcon listItemIcon-transparent material-icons check" aria-hidden="true" style="visibility:${option === currentOption ? 'visible' : 'hidden'};"></span>
            <div class="listItemBody actionsheetListItemBody">
                <div class="listItemBodyText actionSheetItemText">${option}</div>
            </div>
        `;
        button.addEventListener('click', () => selectOption(option));
        return button;
    }

    function openSubmenu() {
        const submenu = document.createElement('div');
        submenu.className = 'dialogContainer';
        submenu.innerHTML = `
            <div class="focuscontainer dialog actionsheet-not-fullscreen actionSheet centeredDialog opened" data-history="true" data-removeonclose="true">
                <div class="actionSheetContent">
                    <div class="actionSheetScroller scrollY">
                    </div>
                </div>
            </div>
        `;

        const scroller = submenu.querySelector('.actionSheetScroller');
        OPTIONS.forEach(option => scroller.appendChild(createSubmenuItem(option)));

        document.body.appendChild(submenu);
        recalculatePosition(scroller);

        submenu.addEventListener('click', (e) => {
            if (e.target === submenu) {
                submenu.remove();
            }
        });
    }

    function selectOption(option) {
        currentOption = option;
        localStorage.setItem(STORAGE_KEY, option);
        console.log(`Introskipper option selected and saved: ${option}`);
        updateMainButton();
        document.querySelector('.dialogContainer').remove();
    }

    function updateMainButton() {
        const button = document.querySelector(`[data-id="${BUTTON_ID}"]`);
        if (button) {
            button.querySelector('.actionSheetItemAsideText').textContent = currentOption;
        }
    }

    function injectMenu(container) {
        if (container.querySelector(`[data-id="${BUTTON_ID}"]`)) return;

        const statsButton = container.querySelector('[data-id="stats"]');
        const menuItem = createMenuItem();

        if (statsButton) {
            statsButton.before(menuItem)
            console.debug("Introskipper menu item injected");
            recalculatePosition(container);
        }
    }

    function recalculatePosition(container) {
        const actionSheet = container.closest('.actionSheet');
        if (!actionSheet) return;

        const dlg = actionSheet;
        const options = {
            positionTo: document.querySelector('.btnVideoOsdSettings'),
            positionY: 'top',
            offsetTop: 0,
            offsetLeft: 0
        };

        const pos = getPosition(options.positionTo, options, dlg);

        if (pos) {
            dlg.style.position = 'fixed';
            dlg.style.margin = '0';
            dlg.style.left = pos.left + 'px';
            dlg.style.top = pos.top + 'px';
        }
    }

    function getPosition(positionTo, options, dlg) {
        const windowSize = getWindowSize();
        const windowHeight = windowSize.innerHeight;
        const windowWidth = windowSize.innerWidth;
        const pos = getOffsets([positionTo])[0];
        if (options.positionY !== 'top') {
            pos.top += (pos.height || 0) / 2;
        }
        pos.left += (pos.width || 0) / 2;
        const height = dlg.offsetHeight || 300;
        const width = dlg.offsetWidth || 160;
        // Account for popup size
        pos.top -= height / 2;
        pos.left -= width / 2;
        // Avoid showing too close to the bottom
        const overflowX = pos.left + width - windowWidth;
        const overflowY = pos.top + height - windowHeight;
        if (overflowX > 0) {
            pos.left -= (overflowX + 20);
        }
        if (overflowY > 0) {
            pos.top -= (overflowY + 20);
        }
        pos.top += (options.offsetTop || 0);
        pos.left += (options.offsetLeft || 0);
        // Do some boundary checking
        pos.top = Math.max(pos.top, 10);
        pos.left = Math.max(pos.left, 10);
        return pos;
    }

    function getWindowSize() {
        return {
            innerHeight: window.innerHeight,
            innerWidth: window.innerWidth
        };
    }

    function getOffsets(elements) {
        return elements.map(el => {
            const rect = el.getBoundingClientRect();
            return {
                top: rect.top,
                left: rect.left,
                width: rect.width,
                height: rect.height
            };
        });
    }

    const observer = new MutationObserver(mutations => {
        for (const mutation of mutations) {
            if (mutation.type === 'childList') {
                const container = mutation.target.querySelector('.actionSheetScroller') ||
                                  (mutation.target.classList.contains('actionSheetScroller') ? mutation.target : null);
                if (container) {
                    injectMenu(container);
                    break;
                }
            }
        }
    });

    observer.observe(document.body, { childList: true, subtree: true });
})();
```

2024-08-29 12:07 UTC, AbandonedCart commented
> I think that I can be a good idea but it would mean that it will only work when the auto skip on the dashboard is off and it would be on the client side, I will try to implement somthing like this. And I think the button/pip should be the default

This was meant to be the configuration page.

2024-08-29 12:26 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                        <div class="checkboxContainer checkboxContainer-withDescription">
That a good question. Even under the intro auto would probably be enough.

- auto skip intros
- auto skip intros in pip
- auto skip credits

2024-08-29 12:52 UTC, jumoog commented
> Alternatively, we could include something like this
> skipmenu.mp4

nice idea

2024-08-29 13:02 UTC, dredstone1 commented
so what to do?
to put the option in the player or in the dashboard?
i think that for now it will be better just leaving it inside the dashboard, and then we can change how the configurations work, in another pull request.
i saw that there is another pull request that is intended to auto skip for android tv... i think that the auto skip option can be remove from the dashboard and replace it with nice list in the player... but that is something that can be done on another pull request, and there we can change how it works more deeply.

2024-08-29 13:52 UTC, dredstone1 commented
i mean that we can remove a lot of settings inside the configuration page in the dashboard by removing all of the setting in the picture and instead adding an option to auto skip on unsupported intro skip button client.
and adding a list of selection into the player.
is that sound good?
![Screenshot 2024-08-29 164800](https://github.com/user-attachments/assets/de4ecdb4-5b4c-4d71-a0f8-d4ab94c94e81)


> so what to do? to put the option in the player or in the dashboard? i think that for now it will be better just leaving it inside the dashboard, and then we can change how the configurations work, in another pull request. i saw that there is another pull request that is intended to auto skip for android tv... i think that the auto skip option can be remove from the dashboard and replace it with nice list in the player... but that is something that can be done on another pull request, and there we can change how it works more deeply.

2024-08-29 14:28 UTC, AbandonedCart commented
You should remove options in settings to place them in the player. That's the fastest way to cause massive confusion. It's either both or just in settings.

2024-08-29 14:38 UTC, dredstone1 commented
ok.
that is exactly what I'm doing right know, i hope i will finish it today.
im using the code that @rlauuzo wrote, in such way that it will check if the auto skip pip is on in the dashboard if it doesn't it will check the option in the player

2024-08-29 15:08 UTC, AbandonedCart commented
There's really no rush.

2024-08-29 16:20 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode = false;
So there is no need for it. You can check the option directly without wasting memory on a variable to store it a second time.

2024-08-29 16:50 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode = false;
i dont want to run this "await this.secureFetch("Intros/UserInterfaceConfiguration");" inside "videoPositionChanged"

2024-08-29 17:25 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        if (this.pip_mode && document.pictureInPictureElement) {
https://github.com/jumoog/intro-skipper/pull/261/files/3ebf788f2e5886f792007d683db866b00017c86f..8f8bb42878a284b957af2f776593503b9fdab9e6#diff-0c80c09409ef66b972d711e22a610e4faa249d514d8db49e7c6d90f3af5e17d8R144

2024-08-29 17:26 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        this.pip_mode = false;
Not asking you to run that.

2024-08-29 17:41 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js
> +        if (this.pip_mode && document.pictureInPictureElement) {
This is something that can always be fixed later, so don’t worry about it.

2024-08-29 18:06 UTC, AbandonedCart commented
If I’m following, you now have a config option for pip. You also have a dynamic item for pip. If either has skipping enabled, it will skip. Seems like that’s going to end up with a case where someone enabled the config, turns it off in the player and can’t figure out why it still skips.

2024-08-29 18:14 UTC, dredstone1 commented
> If I’m following, you now have a config option for pip. You also have a dynamic item for pip. If either has skipping enabled, it will skip. Seems like that’s going to end up with a case where someone enabled the config, turns it off in the player and can’t figure out why it still skips.

Thats right, I'm going to disable the pip only option when the skip intro when using pip is on in the settings,
I personally would want it to always skip in pip,
I think that this is a good solution.

2024-08-29 18:21 UTC, AbandonedCart commented
> I think that this is a good solution.

I think it's too many ideas rolled into one. It's more confusing than it is convenient.

2024-08-29 18:41 UTC, dredstone1 commented
> > I think that this is a good solution.
> 
> I think it's too many ideas rolled into one. It's more confusing than it is convenient.
> 
> If you are going to do both configuration and dynamic as one combined PR, they should work together much cleaner. Configuration should be the default of the dynamic and the dynamic option should either be per session or change the configuration.
> 
> You won't be able to accomplish both using local storage unless you find a way to overwrite it with the configuration at a point that makes sense.

i think that you didnt understand me.
i meant that i will show the "only pip" option if the auto skip pip in the dashboard is off, that will allow to create default option, dont forget that in mobile there isnt pip mode so i must disable it on mobile...

2024-08-29 18:51 UTC, dredstone1 commented
> > I think that this is a good solution.
> 
> I think it's too many ideas rolled into one. It's more confusing than it is convenient.
> 
> If you are going to do both configuration and dynamic as one combined PR, they should work together much cleaner. Configuration should be the default of the dynamic and the dynamic option should either be per session or change the configuration.
> 
> You won't be able to accomplish both using local storage unless you find a way to overwrite it with the configuration at a point that makes sense.

i think that you didnt understand me.
i meant that i will show the "only pip" option if the auto skip pip in the dashboard is off, that will allow to create default option.

2024-08-29 18:58 UTC, AbandonedCart commented
> i think that you didnt understand me. i meant that i will show the "only pip" option if the auto skip pip in the dashboard is off, that will allow to create default option.

That doesn't actually solve the issue, though.

2024-08-29 19:00 UTC, dredstone1 commented
> > i think that you didnt understand me. i meant that i will show the "only pip" option if the auto skip pip in the dashboard is off, that will allow to create default option.
> 
> That doesn't actually solve the issue, though.

why?

2024-08-29 19:19 UTC, AbandonedCart commented
It's still only addressing one scenario. You have multiple options

- No skip
- Skip with button
- Skip with button and PiP
- Skip automatically

You currently have each one in the configuration and then a dynamic option in the player that will skip the intro if auto skip or button w/ pip are *either* selected or enabled in the settings. That dynamic button supports auto, with pip, and never.

What about
- button and never
- button and always
- button with pip and never
- automatically and pip

There are multiple conflicting setups.

2024-08-29 19:22 UTC, dredstone1 commented
> It's still only addressing one scenario. You have multiple options
> 
> * No skip
> * Skip with button
> * Skip with button and PiP
> * Skip automatically
> 
> You currently have each one in the configuration and then a dynamic option in the player that will skip the intro if auto skip or button w/ pip are _either_ selected or enabled in the settings. That dynamic button supports auto, with pip, and never.
> 
> What about
> 
> * button and never
> * button and always
> * button with pip and never
> * automatically and pip
> 
> There are multiple conflicting setups.

im write know working on this and its a bit confusing but its ok and i think tha is work, i will do some more testing and if its working i will commit it

2024-08-29 19:27 UTC, AbandonedCart commented
I think you should take a step back and look at the big picture for a minute.

2024-08-29 19:35 UTC, dredstone1 commented
> I think you should take a step back and look at the big picture for a minute.

ok, i will commit the fixes, and if it will not be good i will remove the option in the dashboard, i think that if it will work as expected it would be better to keep it. at the end i can always remove this part of the code

2024-08-29 20:01 UTC, AbandonedCart commented
Do you know how in your phone you can enable and disable notifications in an app, but then you can also enable and disable them in the system settings?

That is what I'm trying to explain. The configuration page is like system settings and the injected option is like the app settings.

2024-08-29 20:08 UTC, dredstone1 commented
I know, that what my last commit tried to fix, I hope I did it well, I think that it would be a good idea to let the user turn on and off the intro setting as well as setting the default in the dashboard.
The last fix is not good?

2024-08-29 20:11 UTC, AbandonedCart commented
To do what you're doing, the plugin configuration should load as the default and be overridden by the local storage once it's set. Users need some sort of warning that the options in the plugin configuration are server settings and the options in the player are client.

2024-08-29 20:16 UTC, dredstone1 commented
> To do what you're doing, the plugin configuration should load as the default and be overridden by the local storage once it's set. Users need some sort of warning that the options in the plugin configuration are server settings and the options in the player are client.

No!! You didn't try my last fix.
For example:if the option to auto skip if pip is on in the dashboard is on, it Will only show two options in the configuration in the player (only pip, always) if the configuration in the player is set to off and then he changed the configuration in the dashboard to on it will set the local memory the next time he will watch something to only pip...
And more, that what I'm doing...

2024-08-29 20:17 UTC, AbandonedCart commented
I'm really not sure of many more ways to explain it, but you're missing the issue.

2024-08-29 20:25 UTC, dredstone1 commented
You are trying to explain to me that its not a good idea because I'm trying to make the same settings in both client and dashboard and it can conflict with each other and can ovewridden each other? Thats what you ment?

2024-08-29 20:46 UTC, AbandonedCart commented
You don't have to remove anything. It just has to make sense to someone who hasn't read this entire conversation.

2024-08-29 20:58 UTC, dredstone1 commented
And it does, the dashboard configuration let the admin to set a default configuration, it will not let the user click on an option in the player if it's under the minimum configuration, for example if the dashboard is set to auto skip when the player is in pip mode, it will not show the option to Off and it will handle any conflicts, I can had more explanation into the dashboard, it's work also for mobile...

I tried it and it just works(I hope there isn't any other problem that I didn't check).

2024-08-29 21:25 UTC, dredstone1 commented
this is a demonstration, it just work and it show only the option that the user can use depending on the configuration on the dashboard, without any conflicts, 
https://github.com/user-attachments/assets/b37777e7-334f-4127-a512-b35a48b0f417
https://github.com/user-attachments/assets/8f7c7334-c6de-4d79-a341-e74944b6e84e

2024-08-29 22:50 UTC, AbandonedCart commented
Somehow that seems more confusing.

2024-08-29 22:54 UTC, dredstone1 commented
Ok, I realy don't understand why it's confusing, maybe it's just me or maybe it's you, can you tell me what you think would be better😀

2024-08-29 23:05 UTC, AbandonedCart commented
So let me break down the logic of what I was saying and see if that clears it up.

In the configuration, it says 
"Default skip settings. Clients can override this option individually.
Note: Clearing client cache / storage will reset alien setting."
You have auto skip. When selected, the pip option isn't shown.
You have skip with button. When it's selected, you can also select to auto skip in pip.

On the player settings page, the default when no local storage value is saved is the server setting.
Once the user selects an option, that becomes the client option. It is now separate from the server setting. If the user clears their local storage, it returns to the value set by the server (automatically).

Don't skip
Button only
Button w/ Auto Pip
Always Auto

This completely separates the client and the server once the client customized their setting. You no longer have to worry about keeping them aligned.

2024-08-29 23:13 UTC, AbandonedCart commented
What you've got now is somewhere in between where both settings fight for priority. That makes it confusing for the user because they may not understand what they can set where to get the desired results.

Either way, that's just my opinion. It's really up to the other guys.

2024-08-29 23:46 UTC, dredstone1 commented
There is a small problem, write now the auto skip option in the dashboard works in the server side and not in the client side,

We both said almost the same thing:)
what I did is keeping the player configuration separate from the dashboard configuration. 


I thought of somthing, 

In the dashboard there will be one option auto skip when the is not support the skip button, and that's all, and in the client side there will be the 4 option that you wrote, I think that is the simplest thing we can possibly do.
Maybe a few settings for not auto skip the firs episode....
This is just an idea, but what do you thin?

2024-08-29 23:52 UTC, AbandonedCart commented
Does the same problem exist in #263 ?

2024-08-30 05:38 UTC, dredstone1 commented
It's not a problem, he did the options in the client, I did also in the dashboard, like I said I can remove the option from the dashboard and you told me to not do that.

2024-08-30 05:41 UTC, dredstone1 commented
I realy don't think that you tried it, it's realy not confusing, and there is a separation between the dashboard configuration and the client configuration

2024-08-30 05:50 UTC, dredstone1 commented
@jumoog what about you?
It's also confusing for you?

2024-08-30 06:06 UTC, dredstone1 commented
is that better?
![Screenshot 2024-08-30 090620](https://github.com/user-attachments/assets/5f7b0737-1153-41cb-a931-2fb033365fd8)
![Screenshot 2024-08-30 090613](https://github.com/user-attachments/assets/79a8d662-6fda-4fd1-92f2-805c19e5735d)

2024-08-30 08:53 UTC, dredstone1 commented
I actually like your way, to add default settings into the dashboard, I just don't sure what is the best way to implement it,
Should there be an additional option:
-Only button
-don't skip
-always auto
-button and pip
-default

Or it will remmamber if the user changed his player configuration and if he didn't it will synchroniz with the default in the dashboard. 

Which is better?

2024-08-30 10:49 UTC, dredstone1 commented
is that better?
this will let the client the option to choose and it will still let the admin set a default option, for clients who support pip and for those who don't.
ignore the old setting for auto skip for pip.
by default it will set the local memory to default.
is that closer to what you were saing?

https://github.com/user-attachments/assets/d50cc44f-c262-4f45-8924-05391e5e6d78

2024-08-30 16:51 UTC, rlauuzo commented
Could you remove the injected client settings? They’re breaking the TV layout.

2024-08-30 17:20 UTC, dredstone1 commented
how? maybe i can fix it

2024-08-30 22:02 UTC, dredstone1 commented
@AbandonedCart @jumoog is the last commit fixed the confusion?

2024-08-30 23:46 UTC, AbandonedCart commented
This seems like a pretty massive rewrite for a very simple issue.

2024-08-31 05:30 UTC, dredstone1 commented
> This seems like a pretty massive rewrite for a very simple issue.
> 
> The more I think about it, the less I understand why doing auto all the time or simply maximizing the window to press the button and shrink it back down aren't viable alternatives.
> 
> Are you really watching entire seasons in pip and paying close enough attention to notice that 1 - 3 minute intro?

I know we went a bit off topic😀, is changing the name of pr is ok?
I don't want to give up on this

2024-08-31 14:44 UTC, AbandonedCart commented
Besides a checkbox to enable skipping for pip in the configuration, does this provide any additional functionality not provided by #263?

2024-08-31 14:54 UTC, dredstone1 commented
Yes, I understood your point so I removed this checkbox, and I add two option lists, to set the default configuration, one for supported pip and one for unsupported pip.

And a checkbox to enable the client configuration, and a default option int the client configuration to synchroniz with the dashboard configuration.
It also let the user turn off the intro skipper button.

2024-08-31 14:59 UTC, AbandonedCart commented
Besides adding the option to the plugin configuration, does this do anything not already done in #262?

2024-08-31 15:05 UTC, dredstone1 commented
#263?
Adding default option.
Besides that no. 

And I really think that its necessary to have those configurations.

2024-08-31 15:09 UTC, AbandonedCart commented
I think the best option then is to wait on #208, #263, and **then** determine how to proceed here.

2024-08-31 15:20 UTC, dredstone1 commented
Yes exactly.

All of those changes can become one big change.
I just think that we dont need two pr that aim for the same thing.
#261 already have configuration in the dashboard, those configurations can be integrated into #208, because it can auto skip on unsupported intro skipper button depending on those configurations.
That is why I started this conversation in #208

at the end we can always remove the dashboard configuration, so I think it would be better to focus on #261.
I also waiting for a review on the last changes.

2024-08-31 15:24 UTC, AbandonedCart commented
I think you misread. Those changes do not need to become one big change. We can wait for each to be completed and then decide how to handle a configuration option, if one is needed.

2024-08-31 16:02 UTC, dredstone1 commented
OK...

In that case wouldn't it be better to add default options before #208.
because then the #208 can use the default options.

I just think that there is no need to separate the configuration in the dashboard from the configuration on the player.

2024-08-31 16:09 UTC, AbandonedCart commented
It hasn’t been decided whether a PiP option is really necessary on the server side, but as an item in 208 would follow the current layout and make the most sense. It is, after all, a scenario where a button isn’t available, which is exactly what 208 is aimed at addressing.

I also think this PR is currently a mix of @rlauuzo’s code and a configuration option that are over-engineered to somewhat collaborate.

2024-08-31 16:42 UTC, dredstone1 commented
> It hasn’t been decided whether a PiP option is really necessary on the server side, but as an item in 208 would follow the current layout and make the most sense. It is, after all, a scenario where a button isn’t available, which is exactly what 208 is aimed at addressing.
> 
> I also think this PR is currently a mix of @rlauuzo’s code and a configuration option that are over-engineered to somewhat collaborate.


OK, in that case would it better to add the #208 and #263.And then creating in a different pr, the defaults and by that removing the need to auto skip check box, and in general rethinking the configuration in the dashboard. 
Is that sounds better?

2024-08-31 16:45 UTC, AbandonedCart commented
What sounds best is waiting until 208 is merged before worrying about it.

2024-08-31 16:49 UTC, closed without merging