add the option to list the clients to auto skip for (continue #208, #206)
jumoog/intro-skipper pull request #274
Opened 2024-09-05 20:24 UTC by dredstone1

adding the option to set a list of all of the clients name to auto skip for.
setting a default list in the code to always auto skip for.

continue #208 #206

2024-09-05 20:51 UTC, jumoog requested changes

2024-09-05 20:51 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/PluginConfiguration.cs
> +    public string SelectedClients { get; set; } = string.Empty;
you can use a ´List<string>´ here and then you dont need the UnSupportedClients Class anymore

2024-09-05 20:53 UTC, jumoog requested changes

2024-09-05 20:53 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/PluginConfiguration.cs
> +    public string SelectedClients { get; set; } = string.Empty;
and you use `["Android TV", "Kodi"];` instead of `string.Empty`

2024-09-05 20:59 UTC, AbandonedCart commented
@jumoog You didn’t get to it fast enough.

2024-09-05 21:03 UTC, AbandonedCart commented
According to https://github.com/jumoog/intro-skipper/issues/206, there is also JellyCon

2024-09-05 21:07 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                                Enter the names of clients to automatically skip intros for, separated by commas.<br />
This probably isn’t a good idea at the moment. Libraries get away with it because the user sets the name and it’s on them to copy it over correctly. You’re asking the user to set the client exactly as the client identifies itself (capitalization, spacing, etc)

2024-09-05 21:07 UTC, dredstone1 commented
I will fix the requests,
I just want to clarify something, the admin can add to hard coded list (android TV, kodi..) more clients or the admin can add any client that he wants and remove any client that he wants from the list?

2024-09-05 21:12 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                                Enter the names of clients to automatically skip intros for, separated by commas.<br />
OK, I Will add them as checkbox or something like that

2024-09-05 21:14 UTC, jumoog commented
> I will fix the requests, I just want to clarify something, the admin can add to hard coded list (android TV, kodi..) more clients or the admin can add any client that he wants and remove any client that he wants from the list?

The admin can add/remove any client. `["Android TV", "Kodi"]` is the default. The default is used only once. A save will override this (this is handled by the plugin framework).

2024-09-05 21:16 UTC, AbandonedCart commented
Probably needs instructions or a link to instructions on how to get the name

2024-09-05 21:17 UTC, jumoog commented
> According to #206, there is also JellyCon

We can extend this list in the future. I always check that the client in question really does not have a button.

2024-09-05 21:24 UTC, dredstone1 commented
I think i will add a list of all of the current unsupported clients, and an add button, the add button will open a list of all of the clients, and the admin can click on it and it will add it to the unsupported list, and on every client on the list there will be an X that will remove it from the list. 
Is that sound good?

2024-09-05 21:33 UTC, jumoog commented
I personaly like this style: https://jumoog.io/demo.html
Feel free to do whatever you like. Just remember that people use it on the phone too.

2024-09-05 21:39 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                                Enter the names of clients to automatically skip intros for, separated by commas.<br />
You already get `Devices` you can use the info (AppName)

2024-09-05 21:43 UTC, jumoog commented
I'm glad to see you contribute, because I hate Frontend with a passion. 😄

2024-09-05 21:45 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                                Enter the names of clients to automatically skip intros for, separated by commas.<br />
Does that list all clients that have connected?

2024-09-05 21:46 UTC, AbandonedCart commented
And now I can delay updating even further.

2024-09-05 21:55 UTC, dredstone1 commented
Its look good, I will do this, with a bit change, I will add the option "add" to add custom client name.

2024-09-05 22:01 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                                Enter the names of clients to automatically skip intros for, separated by commas.<br />
Yes it does, I will change it as I'm doing the two columns idea.

2024-09-06 17:43 UTC, dredstone1 commented
another small clarification, it will save only the clients who marked as autoskip or it will save all the clients?, so if the admin marked a certain client as not auto skip and no one used this client for some time, it will remove it from the device list, and it can cause confusion?

2024-09-06 18:23 UTC, jumoog commented
hmm using `List<>` gives me the warning `CA2227` and `CA1002`

2024-09-06 18:24 UTC, dredstone1 commented
i know i use Collection

2024-09-06 18:36 UTC, dredstone1 commented
i think that collection is also not going to work, because it also not letting me add set, only get.
i  wii search for something else

2024-09-06 19:22 UTC, dredstone1 commented
from what i read, its look like we will need to use one big string insted of using a list of strings

2024-09-06 20:04 UTC, jumoog commented
if you want just supress CA2227 and CA1002

2024-09-06 20:08 UTC, dredstone1 commented
if its not a problem, ok. that is why c is the best

2024-09-06 20:09 UTC, jumoog commented
Sorry for all the confusion, I actually program almost everything in golang/javascript/c++ and occasionally c# at work. I don't know all the weird Microsoft warnings. 🫤

2024-09-06 20:14 UTC, dredstone1 commented
its ok, me too, i prefer c or python, it took me a full hour and another half a hour with gpt to figure out the problem

2024-09-07 21:01 UTC, dredstone1 commented
is this a good idea to add an option to add custom client name through the ui or if someone would get into the situation were he need to use custom client name he can just add it manually through the configuration file or through debug mode?

2024-09-07 21:16 UTC, jumoog commented on .editorconfig
> +
not needed

2024-09-07 21:18 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/PluginConfiguration.cs
> -    public string SelectedClients { get; set; } = string.Empty;
```c#
#pragma warning disable CA1002
#pragma warning disable CA2227
    public List<string> ClientList { get; set; } = ["Android TV", "Kodi"];
#pragma warning restore CA2227
#pragma warning restore CA1002
```

2024-09-07 21:18 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
why set it here?

2024-09-07 21:24 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
there is a wired problem that when jellyfin start its just add the data from the file to the ClientList and not setting it, i couldn't fix it, its just so weird

2024-09-07 21:28 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/PluginConfiguration.cs
> -    public string SelectedClients { get; set; } = string.Empty;
ok

2024-09-07 21:28 UTC, dredstone1 commented on .editorconfig
> +
ok

2024-09-07 21:36 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
It worked in tests. I think you ran into the problem that once `ClientList` is in `ConfusedPolarBear.Plugin.IntroSkipper.xml` defined you cannot change the default value. If you want to test it, the easiest way is to manually delete ClientList from the xml file and restart jellyfin.

2024-09-07 21:36 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
![grafik](https://github.com/user-attachments/assets/aa015f50-33eb-4c17-bb7a-59d45ed58b4b)

2024-09-07 21:41 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
do that:
run jellyfin with out ClientList.
then click save in the dashboard.
then stop jellyfin.
then run jellyfin.
then you will see android tv and kody in adition to what was set before.

2024-09-07 21:48 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
its didnt happen to you?

2024-09-07 22:23 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                            <label>Set clients to auto skip for.</label> <br />
This is a bit misleading. The feature is meant to set client that will *always* auto skip even when the button is enabled. How this reads is that it replaces the auto skip feature. "Auto skip" (the feature) should still auto skip for all clients.

2024-09-07 22:25 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
Is the issue that you're setting the variable every time instead of only setting it when nothing loads?

2024-09-07 22:25 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
i'll do some test tomorrow

2024-09-07 22:25 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                            <label>Set clients to auto skip for.</label> <br />
I forgot to change that

2024-09-07 22:32 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
I didnt understand you, the issue is, when you already save once and than you restart jellyfin it will load the xml file to the configuration not by setting the list instead by adding to the list, i think that is something to do with the set, instead of set the list is adding to the list, try to set the list to only android TV through the plugin.cs you will see that it just adding to the list, it only setting it when you click save, I don't know why it's happening

2024-09-07 22:32 UTC, dredstone1 commented
> is this a good idea to add an option to add custom client name through the ui or if someone would get into the situation were he need to use custom client name he can just add it manually through the configuration file or through debug mode?

What about that?

2024-09-07 22:55 UTC, AbandonedCart commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
I was saying you shouldn't "set" the list if it isn't blank and that should solve it.

2024-09-07 22:57 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
I can't remove or clean it

2024-09-07 22:57 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
I also think that my fix is also not good

2024-09-08 06:30 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Configuration/configPage.html
> +                            <label>Set clients to auto skip for.</label> <br />
I'm sory, but I didn't read that correct, I thought I forgot to remove the description😂.
I think that the autoskip checkbox ment to auto skip when there was an error and to enable auto skip per client.
I will change the description of the auto skip checkbox.

2024-09-08 06:42 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
this is the problem


https://github.com/user-attachments/assets/d4ae3ed5-3da0-40fb-ada6-af9880170ce5

2024-09-08 13:53 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
Ok i have that problem as well

2024-09-08 14:08 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
Im thinking of a few way to handle this,
Using the first way I did, it will to need compare the strings every time to check if you changed the list.
Or I don't know how to fix it...

2024-09-08 14:09 UTC, dredstone1 commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
I can also add another veriable to the configuration so when the list has changed In the dashboard it will set it to true and it will update the list

2024-09-08 14:35 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs
> +        if (Instance.Configuration.ClientList.Count == 1 && Instance.Configuration.ClientList[0] == "default")
sorry i didn't know that `List<string>` has that problem

2024-09-08 14:42 UTC, jumoog commented
ok lets pick #277 and give @dredstone1 credit as Co-Author

2024-09-08 14:43 UTC, closed without merging

2024-09-08 14:45 UTC, jumoog commented
Thanks for your PR @dredstone1. You have too many tabs open.

2024-09-08 14:53 UTC, dredstone1 commented
I'm sory I using arc or edge but arc have to bugs, and edge is edge.
So I now using chrome, and I hate it. I want tabs on the side.