Feature/autoskip credits
jumoog/intro-skipper pull request #98
Opened 2024-03-30 09:18 UTC by phyzical

Untested, very rough POC

the one thing i couldnt figure out is how to sepeate the dep on "AutoSkip" so that we can have two settings for credits and intros

as i cannot figure out how autoskip is initialized to make "type" part of the class as a whole.

if someone can point me in that direction ill change this pr to initlise two autoskip classes instead

2024-03-30 10:18 UTC, jumoog commented
Thank you!

2024-03-30 10:34 UTC, jumoog requested changes

2024-03-30 10:34 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs
> +            Skip(sender, e,"intro", _sentIntroSeekCommandLock, !Plugin.Instance!.Intros, Plugin.Instance!.Configuration.AutoSkipIntroNotificationText)
Please add missing ";"

2024-03-30 10:34 UTC, jumoog commented on ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs
> +            Skip(sender, e,"credit", _sentCreditsSeekCommandLock, !Plugin.Instance!.Credits, Plugin.Instance!.Configuration.AutoSkipCreditsNotificationText)
Please add missing ";"

2024-03-30 10:51 UTC, phyzical commented on ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs
> +            Skip(sender, e,"intro", _sentIntroSeekCommandLock, !Plugin.Instance!.Intros, Plugin.Instance!.Configuration.AutoSkipIntroNotificationText)
```suggestion
            Skip(sender, e,"intro", _sentIntroSeekCommandLock, !Plugin.Instance!.Intros, Plugin.Instance!.Configuration.AutoSkipIntroNotificationText);
```

2024-03-30 10:51 UTC, phyzical commented on ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs
> +            Skip(sender, e,"credit", _sentCreditsSeekCommandLock, !Plugin.Instance!.Credits, Plugin.Instance!.Configuration.AutoSkipCreditsNotificationText)
```suggestion
            Skip(sender, e,"credit", _sentCreditsSeekCommandLock, !Plugin.Instance!.Credits, Plugin.Instance!.Configuration.AutoSkipCreditsNotificationText);
```

2024-03-30 11:02 UTC, jumoog commented
Did you try to compile the code before committing?

2024-03-30 11:07 UTC, phyzical commented
no as i stated untested poc, was hoping for some guidance around refactoring it better to have two skippers inilisedisntead of merging them together inside, due to the setting for enabling autoskip being a core part of the class

2024-03-30 11:12 UTC, phyzical commented
But if we dont care about that ill do a proper test i suppose this plugin will be redundant soon anwyay

2024-03-30 11:16 UTC, jumoog commented
> But if we dont care about that ill do a proper test i suppose this plugin will be redundant soon anwyay

Unfortunately not! Media segements didn't make it into 10.9. and won't arrive until 10.10. At the current rate, that means in 2 years 😄

2024-03-30 11:30 UTC, AbandonedCart commented
> Unfortunately not! Media segements didn't make it into 10.9.

The guy "writing it" is mostly stumbling through it and it seems like the team that needs to approve it is still bickering amongst themselves about how they want it to work. They had a whole mess of changes and were trying to rush him before they locked the code for 10.9, which allowed zero time for real testing. There was no way.

2024-03-30 11:46 UTC, phyzical commented
guess what i mean is do we care if its kinda botched to pretend that credits are "intro" . looking at other parts that seems to be whats done so im leading toward the meh column

2024-03-30 11:49 UTC, jumoog commented
Yes, that should refactor the code anyway

2024-03-30 11:51 UTC, jumoog submitted a review, later dismissed

2024-03-30 11:52 UTC, phyzical commented
once my credits processing is done, ill compile this and make sure it works as expected.

2024-03-30 11:54 UTC, jumoog commented
The tricky part is always migrating the old data.

2024-03-30 11:59 UTC, phyzical commented
we can only ditch he custom text for credits and reuse the intro text instead tbh

2024-03-30 12:03 UTC, AbandonedCart commented
Somewhere in the original code, it was explained about why credits are actually based on intros.

2024-03-30 12:03 UTC, jumoog commented
To be honest, I have not bothered with the code. I have seen that the old repo has been archived. Since I use the plugin anyway, I made a fork and made sure that the dependencies are updated.

2024-03-30 12:03 UTC, phyzical commented
if i was to guess credits are intros... but in reverse 😆

2024-03-30 12:04 UTC, AbandonedCart commented
No. It was something to do with how the credit placement is determined.

2024-03-30 12:05 UTC, jumoog commented
only when the code no longer worked with 10.9 did i start looking at the code 😄

2024-03-30 12:07 UTC, AbandonedCart commented
Still better than the project I am working on where the guy intentionally breaks code just to write something.

2024-03-30 12:24 UTC, jumoog commented
> Still better than the project I am working on where the guy intentionally breaks code just to write something.

lol but Hacktoberfest is already over

2024-03-31 03:02 UTC, phyzical commented
@jumoog 
![image](https://github.com/jumoog/intro-skipper/assets/5182053/e62de7fc-805e-4bc2-b2f0-00b32101b654)
any idea how to get around this build error?

2024-04-01 04:07 UTC, phyzical commented
@jumoog 
![image](https://github.com/jumoog/intro-skipper/assets/5182053/e62de7fc-805e-4bc2-b2f0-00b32101b654)
any idea how to get around this build error?

2024-04-01 04:07 UTC, closed without merging

2024-04-01 04:07 UTC, phyzical commented
reopened fresh of master